const products = [
  { name: "Visa Gift Card", price: "From ₹500" },
  { name: "Mastercard Gift Card", price: "From ₹500" },
  { name: "American Express Gift Card", price: "From ₹1000" },
  { name: "Amazon Gift Card", price: "From ₹100" },
  { name: "Google Play Gift Card", price: "From ₹100" },
  { name: "Apple Gift Card", price: "From ₹1000" },
  { name: "Steam Gift Card", price: "From ₹250" },
  { name: "Xbox Gift Card", price: "From ₹500" },
  { name: "PlayStation Gift Card", price: "From ₹500" },
  { name: "Nintendo eShop Card", price: "From ₹1000" },
  { name: "Netflix Gift Card", price: "From ₹500" },
  { name: "Spotify Gift Card", price: "From ₹119" },
  { name: "Razer Gold", price: "From ₹250" },
  { name: "Garena Shells", price: "From ₹100" },
  { name: "Free Fire Diamonds", price: "From ₹80" },
  { name: "BGMI UC", price: "From ₹75" },
];
